<?php


/**
 * @since 2.7
 * @package Arlima
 */
class Arlima_WP_Page_Edit extends Arlima_WP_AbstractAdminPage {

    function scripts()
    {
        return array(
            'arlima-js' => array('url' =>ARLIMA_PLUGIN_URL . 'js/page-edit.js', 'deps'=>array('jquery')),
            'jquery-form-validator' => array('url' => '//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.1.47/jquery.form-validator.min.js', 'deps'=>array('jquery'))
        );
    }

    function styleSheets()
    {
        return array(
            'arlima_css' => array('url'=>ARLIMA_PLUGIN_URL . 'css/admin.css', 'deps'=>array()),
        );
    }

    function getName()
    {
        return __('Edit lists', 'arlima');
    }

    function getMenuName()
    {
        return __('Edit lists', 'arlima');
    }

    function slug()
    {
        return 'arlima-edit';
    }

    public function parentSlug()
    {
        return 'arlima-main';
    }

    public function capability()
    {
        return 'manage_options';
    }

    public function enqueueScripts()
    {
        parent::enqueueScripts(); // TODO: Change the autogenerated stub
        add_action('admin_footer', array($this, 'addFormValidation'));
    }

    public function addFormValidation()
    {
        ?>
        <script>
            jQuery.validate({
                borderColorOnError :''
            });
        </script>
        <?php
    }

}
